name: glz
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - asttokens=3.0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.20
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.4
  - fontconfig=2.15.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libcups=2.4.15
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.22.1
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.54
  - libpq=17.6
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy-base=2.4.2
  - openldap=2.6.12
  - openssl=3.6.1
  - packaging=25.0
  - parso=0.8.6
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=26.0.1
  - pixman=0.46.4
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readline=8.3
  - scipy=1.16.3
  - setuptools=80.10.2
  - sip=6.12.0
  - six=1.17.0
  - spirv-tools=2025.1
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wayland=1.24.0
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - brotli==1.2.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - defusedxml==0.7.1
      - fastapi==0.129.0
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.21.2
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2026.2.0
      - gradio==6.5.1
      - gradio-client==2.0.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.1
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mistune==3.2.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nbstripout==0.9.0
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - orjson==3.11.7
      - overrides==7.7.0
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - pillow==12.1.1
      - platformdirs==4.7.0
      - prometheus-client==0.24.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyparsing==3.3.2
      - python-json-logger==4.0.0
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - safehttpx==0.1.7
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - shellingham==1.5.4
      - soupsieve==2.8.3
      - starlette==0.52.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomlkit==0.13.3
      - tqdm==4.67.3
      - typer==0.23.1
      - typer-slim==0.23.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==3.6.10
prefix: /home/elias/miniconda3/envs/glz
